''' THIS FILE CONTAINS THE SENSITIVE INFORMATION THAT SHOULD BE
    KEPT ON YOUR LOCAL MACHINE OR IN A .gitignore file'''
ACCOUNT_SID = **INSERT ACCOUNT_SID FROM TWILIO HERE**
AUTH_TOKEN = **INSERT AUTH_TOKEN FROM TWILIO HERE**
PHONE_NUMBER = **INSERT PHONE NUMBER HERE**
